### ISSUE TITLE
LaTex Documentation Template

### ISSUE THREAD

**Issue by 0xisk** [blockboard/ThreatMapper#16]
Choose a LaTex template.

**Comment by 0xisk** [comment]
I've chosen the following LaTex templates from these collections [Overleaf Gallery — Project / Lab Report](https://www.overleaf.com/gallery/tagged/report): 

- [Template 1](https://www.overleaf.com/latex/templates/proposta-apostila-iff-itaperuna/yctvxtkzqhpw)

- [Template 2](https://www.overleaf.com/latex/templates/report-template-mcyber/ccxytdfzkywc) 

- [Template 3](https://www.overleaf.com/latex/templates/miunthes-thesis-template-for-mid-sweden-university/cxkrvtvnzpvf)

Please @kirollosBoles @blockboard-co review those options, and also you may take a look at the whole collections. You can download the template as a PDF to allow you to see it in action.

**Comment by blockboard-co** [comment]
Thanks Alex, 
Let's go with Template 2. 
@kirollosBoles Please follow.

**Comment by 0xisk** [comment]
Ok great, we will stick to the second template.
https://www.overleaf.com/latex/templates/report-template-mcyber/ccxytdfzkywc
