### ISSUE TITLE
Installing GitLab

### ISSUE THREAD

**Issue by 0xisk** [blockboard/ThreatMapper#18]
We need to install GitLab on our machines.

**Comment by mina98** [comment]
Already installed.

**Comment by 0xisk** [comment]
Please @mina98 I need to know your current version.

**Comment by mina98** [comment]
@iskanderandrew  the version is 13.3.0-ee

**Comment by kirollosBoles** [comment]
@iskanderandrew done it with version 13.3.0-ee
