### ISSUE TITLE
Installing Docker & Docker-Compose

### ISSUE THREAD

**Issue by 0xisk** [blockboard/ThreatMapper#2]
We need to install Docker tools on our machines.

**Comment by mina98** [comment]
I installed Docker with version :19.03.12

**Comment by 0xisk** [comment]
I've installed Docker and Docker-Compose. 

- Docker 
![pic-selected-200818-1156-22](https://user-images.githubusercontent.com/36774944/90510600-c8bed300-e14a-11ea-9421-4ca10fa55175.png)

- Docker-Compose
![pic-selected-200818-1156-30](https://user-images.githubusercontent.com/36774944/90510629-d1170e00-e14a-11ea-93e4-ee357478cfeb.png)

**Comment by 0xisk** [comment]
Great @mina98, can you install Docker-Compose as well. We shall need it.

**Comment by mina98** [comment]
@iskanderandrews Done.

**Comment by kirollosBoles** [comment]
@iskanderandrews  @mina98  
I have done it and same versions
Docker engine 19.03.12
Docker compose 1.26.2

**Comment by 0xisk** [comment]
Great @kirollosBoles :100:
