### ISSUE TITLE
Search about Virtual private cloud (VPC)

### ISSUE THREAD

**Issue by kirollosBoles** [blockboard/ThreatMapper#20]
Searching about Virtual private cloud (VPC) fro installing Management Console.

**Comment by kirollosBoles** [comment]
@iskanderandrew  it is a private network 
So we will deploy  management console on compute engine and VPC provide connectivity for the engine

**Comment by 0xisk** [comment]
@kirollosBoles Please provide me with useful shortcut resources.

**Comment by kirollosBoles** [comment]
@iskanderandrew https://cloud.google.com/vpc/docs/vpc
