### ISSUE TITLE
Exploring GitLab

### ISSUE THREAD

**Issue by 0xisk** [blockboard/ThreatMapper#23]
Exploring and practicing more on GitLab

**Comment by mina98** [comment]
@iskanderandrew  @kirollosBoles 
For how to build the images using GitLab-cli and how to integrate it. Look to this [link](https://www.youtube.com/watch?v=mhRmdI0I4Bc)
For use GitLab CI/CD this [docs](https://docs.gitlab.com/ee/ci/) explain it.

To use the [simple_go_server](https://gitlab.com/deepfence-gitlab/simple_go_server) provided from deepfence, should have the IP of deepfence management console and it is not provided now.
