### ISSUE TITLE
Errors: CircleCI build error

### ISSUE THREAD

**Issue by 0xisk** [blockboard/ThreatMapper#26]
Listing and discussing CircleCI build errors.

**Comment by iskanderandrews** [comment]
```
#!/bin/bash -eo pipefail
cd client
yarn install
yarn run lint
yarn test
yarn install v1.21.1
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.46s.
yarn run v1.21.1
$ eslint app server.js && stylelint app/scripts
/home/weave/scope/client/app/scripts/components/node-details.js
  394:5  warning  Unexpected console statement  no-console
/home/weave/scope/client/app/scripts/components/sidebar.js
  28:24  warning  Unexpected alert  no-alert
  37:24  warning  Unexpected alert  no-alert
  46:24  warning  Unexpected alert  no-alert
  55:24  warning  Unexpected alert  no-alert
/home/weave/scope/client/app/scripts/router.js
  63:7  warning  Unexpected alert  no-alert
/home/weave/scope/client/app/scripts/routes/Integration.js
  3:16  error  'Integration' is not defined                                                                           no-undef
  3:36  error  Unexpected block statement surrounding arrow body; move the returned value immediately after the `=>`  arrow-body-style
  4:1   error  Expected indentation of 2 spaces but found 3                                                           indent
  5:7   error  Expected indentation of 5 space characters but found 6                                                 react/jsx-indent
  6:10  error  Expected indentation of 8 space characters but found 9                                                 react/jsx-indent
  8:1   error  Expected indentation of 2 spaces but found 3                                                           indent
  9:2   error  Newline required at end of file but not found                                                          eol-last
  9:2   error  Missing semicolon                                                                                      semi
/home/weave/scope/client/app/scripts/routes/Management.js
  3:16  error  'Management' is not defined                                                                            no-undef
  3:35  error  Unexpected block statement surrounding arrow body; move the returned value immediately after the `=>`  arrow-body-style
  4:1   error  Expected indentation of 2 spaces but found 3                                                           indent
  5:7   error  Expected indentation of 5 space characters but found 6                                                 react/jsx-indent
  6:10  error  Expected indentation of 8 space characters but found 9                                                 react/jsx-indent
  8:1   error  Expected indentation of 2 spaces but found 3                                                           indent
  9:2   error  Newline required at end of file but not found                                                          eol-last
  9:2   error  Missing semicolon                                                                                      semi
/home/weave/scope/client/app/scripts/routes/Register.js
  3:16  error  'Register' is not defined                                                                              no-undef
  3:33  error  Unexpected block statement surrounding arrow body; move the returned value immediately after the `=>`  arrow-body-style
  4:1   error  Expected indentation of 2 spaces but found 3                                                           indent
  5:7   error  Expected indentation of 5 space characters but found 6                                                 react/jsx-indent
  6:10  error  Expected indentation of 8 space characters but found 9                                                 react/jsx-indent
  8:1   error  Expected indentation of 2 spaces but found 3                                                           indent
  9:2   error  Newline required at end of file but not found                                                          eol-last
  9:2   error  Missing semicolon                                                                                      semi
/home/weave/scope/client/server.js
  9:8  error  'exec' is assigned a value but never used  no-unused-vars
✖ 31 problems (25 errors, 6 warnings)
  21 errors and 0 warnings potentially fixable with the `--fix` option.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by RewasReda** [comment]
@iskanderandrews i'm pretty sure that the error is syntax based and we can fix it in a call with share screen since i can't open the code on windows currently

**Comment by RewasReda** [comment]
@iskanderandrews  /home/weave/scope/client/app/scripts/components/node-details.js
  394:5  warning  Unexpected console statement  no-console
/home/weave/scope/client/app/scripts/components/sidebar.js
  28:24  warning  Unexpected alert  no-alert
  37:24  warning  Unexpected alert  no-alert
  46:24  warning  Unexpected alert  no-alert
  55:24  warning  Unexpected alert  no-alert

**Comment by iskanderandrews** [comment]
> @iskanderandrews /home/weave/scope/client/app/scripts/components/node-details.js
> 394:5 warning Unexpected console statement no-console
> /home/weave/scope/client/app/scripts/components/sidebar.js
> 28:24 warning Unexpected alert no-alert
> 37:24 warning Unexpected alert no-alert
> 46:24 warning Unexpected alert no-alert
> 55:24 warning Unexpected alert no-alert

Solved :100:

**Comment by RewasReda** [comment]
@iskanderandrews /home/weave/scope/client/app/scripts/router.js
  63:7  warning  Unexpected alert  no-alert
/home/weave/scope/client/app/scripts/routes/Integration.js
  3:16  error  'Integration' is not defined                                                                           no-undef
  3:36  error  Unexpected block statement surrounding arrow body; move the returned value immediately after the `=>`  arrow-body-style
  4:1   error  Expected indentation of 2 spaces but found 3                                                           indent
  5:7   error  Expected indentation of 5 space characters but found 6                                                 react/jsx-indent
  6:10  error  Expected indentation of 8 space characters but found 9                                                 react/jsx-indent
  8:1   error  Expected indentation of 2 spaces but found 3                                                           indent
  9:2   error  Newline required at end of file but not found                                                          eol-last
  9:2   error  Missing semicolon                                                                                      semi
/home/weave/scope/client/app/scripts/routes/Management.js
  3:16  error  'Management' is not defined                                                                            no-undef
  3:35  error  Unexpected block statement surrounding arrow body; move the returned value immediately after the `=>`  arrow-body-style
  4:1   error  Expected indentation of 2 spaces but found 3                                                           indent
  5:7   error  Expected indentation of 5 space characters but found 6                                                 react/jsx-indent
  6:10  error  Expected indentation of 8 space characters but found 9                                                 react/jsx-indent
  8:1   error  Expected indentation of 2 spaces but found 3                                                           indent
  9:2   error  Newline required at end of file but not found                                                          eol-last
  9:2   error  Missing semicolon                                                                                      semi
/home/weave/scope/client/app/scripts/routes/Register.js
  3:16  error  'Register' is not defined                                                                              no-undef
  3:33  error  Unexpected block statement surrounding arrow body; move the returned value immediately after the `=>`  arrow-body-style
  4:1   error  Expected indentation of 2 spaces but found 3                                                           indent
  5:7   error  Expected indentation of 5 space characters but found 6                                                 react/jsx-indent
  6:10  error  Expected indentation of 8 space characters but found 9                                                 react/jsx-indent
  8:1   error  Expected indentation of 2 spaces but found 3                                                           indent
  9:2   error  Newline required at end of file but not found                                                          eol-last
  9:2   error  Missing semicolon

**Comment by RewasReda** [comment]
@iskanderandrews /home/weave/scope/client/app/scripts/routes/Integration.js
  3:16  error  'Integration' is not defined                                                                           no-undef
  3:36  error  Unexpected block statement surrounding arrow body; move the returned value immediately after the `=>`  arrow-body-style
  4:1   error  Expected indentation of 2 spaces but found 3                                                           indent
  5:7   error  Expected indentation of 5 space characters but found 6                                                 react/jsx-indent
  6:10  error  Expected indentation of 8 space characters but found 9                                                 react/jsx-indent
  8:1   error  Expected indentation of 2 spaces but found 3                                                           indent
  9:2   error  Newline required at end of file but not found                                                          eol-last
  9:2   error  Missing semicolon

**Comment by RewasReda** [comment]
@iskanderandrews 
/home/weave/scope/client/app/scripts/routes/Management.js
  3:16  error  'Management' is not defined                                                                            no-undef
  3:35  error  Unexpected block statement surrounding arrow body; move the returned value immediately after the `=>`  arrow-body-style
  4:1   error  Expected indentation of 2 spaces but found 3                                                           indent
  5:7   error  Expected indentation of 5 space characters but found 6                                                 react/jsx-indent
  6:10  error  Expected indentation of 8 space characters but found 9                                                 react/jsx-indent
  8:1   error  Expected indentation of 2 spaces but found 3                                                           indent
  9:2   error  Newline required at end of file but not found                                                          eol-last
  9:2   error  Missing semicolon

**Comment by RewasReda** [comment]
@iskanderandrews 
/home/weave/scope/client/app/scripts/routes/Register.js
  3:16  error  'Register' is not defined                                                                              no-undef
  3:33  error  Unexpected block statement surrounding arrow body; move the returned value immediately after the `=>`  arrow-body-style
  4:1   error  Expected indentation of 2 spaces but found 3                                                           indent
  5:7   error  Expected indentation of 5 space characters but found 6                                                 react/jsx-indent
  6:10  error  Expected indentation of 8 space characters but found 9                                                 react/jsx-indent
  8:1   error  Expected indentation of 2 spaces but found 3                                                           indent
  9:2   error  Newline required at end of file but not found                                                          eol-last
  9:2   error  Missing semicolon

**Comment by RewasReda** [comment]
@iskanderandrews 
/home/weave/scope/client/server.js
  9:8  error  'exec' is assigned a value but never used  no-unused-vars
