### ISSUE TITLE
Installing Jenkins

### ISSUE THREAD

**Issue by 0xisk** [blockboard/ThreatMapper#3]
We need to install Jenkins on our machines.

**Comment by mina98** [comment]
I installed Jenkins  "version : 2.235.5"

**Comment by 0xisk** [comment]
I've installed 'Jenkins' successfully.
Here is a screenshot with Package details.
![pic-selected-200818-1146-43](https://user-images.githubusercontent.com/36774944/90509784-6913f800-e149-11ea-8a28-52e214aa11db.png)

**Comment by iskanderandrews** [comment]
Great @mina98 😀

**Comment by kirollosBoles** [comment]
@iskanderandrews  @mina98 i have done it with version 2.253
