### ISSUE TITLE
Installing CircleCI

### ISSUE THREAD

**Issue by 0xisk** [blockboard/ThreatMapper#4]
We need to install CircleCi on our machines.

**Comment by mina98** [comment]
I installed CircleCI with version 0.1.9321

**Comment by iskanderandrews** [comment]
Great @mina98 😀

**Comment by 0xisk** [comment]
Installed CircleCI version _0.1.9321-1_

![pic-selected-200821-2125-06](https://user-images.githubusercontent.com/36774944/90936903-c338e580-e3f5-11ea-89ce-55d84276c7e7.png)

**Comment by 0xisk** [comment]
@kirollosBoles did you install that?

**Comment by kirollosBoles** [comment]
@iskanderandrew Yes

**Comment by 0xisk** [comment]
@kirollosBoles Please post your current running version.

**Comment by kirollosBoles** [comment]
@iskanderandrew   0.1.9321
