### ISSUE TITLE
Exploring Microsoft Azure cloud tools

### ISSUE THREAD

**Issue by 0xisk** [blockboard/ThreatMapper#7]
We need to have more information about the different capabilities and options that Microsoft Azure cloud tools provides.

**Comment by 0xisk** [comment]
Please @mina98 I need information from their cloud capabilities according to what we need in order to test ThreatMapper. So make that to be your target on information gathering. Also, we will at our next meeting create an account on Microsoft Azure, so I will need a shortcut on how do we will do that, and also what kind of tools do we need.

**Comment by mina98** [comment]
For check the all features of Microsoft Azure Cloud tools: [Azure Documentation](https://docs.microsoft.com/en-us/azure/?product=featured)
Microsoft Azure has more than 25 free services, 12 months of free products and $200 credit to experiment with any Azure service in the first 30 days.

If we use Linux Virtual Machines within the free services, we will get 750 hours.

If we want to buy Virtual Machines services : [Pricing of Virtual Machine services](https://azure.microsoft.com/en-us/pricing/calculator/?service=virtual-machines)

**Comment by 0xisk** [comment]
Thanks @mina98, you can also search for `Azure Container Registry` #11 
Also, I need you to be ready for creating an account for Blockboard on the Azure and register on the services you see that will benefit us on the scope of the project.

**Comment by mina98** [comment]
In Azure Kubernetes Services, the deepfence agents are deployed as a daemonset in the cluster. 
The Supported Kubernetes versions in Azure Kubernetes Service (AKS) is 1.17,1.18. You can check this [link](https://docs.microsoft.com/en-us/azure/aks/supported-kubernetes-versions )

For the` Azure Container Registry`  #11, I think this [link](https://docs.microsoft.com/en-us/azure/container-registry/) will be good it contains the features and how to start and manage. Azure Container Registry allows you to build, store, and manage container images and artifacts in a private registry for all types of container deployments. 
The key features 
- Create one or more container registries in your Azure subscription.
- For security : Azure Container Registry transfers container images over HTTPS, and supports TLS to secure client connections.
- Supported images and artifacts
- Automated image builds

**Comment by 0xisk** [comment]
Thanks @mina98 for your great work :100:
