### ISSUE TITLE
Installing Kubernetes

### ISSUE THREAD

**Issue by 0xisk** [blockboard/ThreatMapper#8]
We need to install Kubernetes tools on our machines.

**Comment by 0xisk** [comment]
I've successfully installed the Kubernetes client Ctl tool according to my Arch Linux machine. 
![pic-selected-200818-1159-31](https://user-images.githubusercontent.com/36774944/90510949-4b479280-e14b-11ea-9836-8d01491c9155.png)

**Comment by mina98** [comment]
I've successfully installed Kubernetes client with version 1.18.5

**Comment by kirollosBoles** [comment]
@iskanderandrews  @mina98 i have done with same version
